# Generated by Django 4.2.1 on 2023-06-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperture", models.FloatField()),
                ("max_length", models.IntegerField()),
                ("frequency_penalty", models.FloatField()),
                ("presence_penalty", models.FloatField()),
                ("top_p", models.FloatField()),
                ("model_name", models.CharField(max_length=200)),
            ],
        ),
    ]
