# Generated by Django 4.2.1 on 2023-06-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0005_alter_countsubcriber_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField()),
                ("created_at", models.DateField()),
                ("day", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="countunsubcriber",
            name="created_at",
            field=models.DateField(),
        ),
    ]
