# Generated by Django 4.2.1 on 2023-06-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0007_userchat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userchat",
            name="status",
            field=models.IntegerField(max_length=1, null=True),
        ),
    ]
