# Generated by Django 4.2.1 on 2023-06-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0009_alter_userchat_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userchat",
            name="status",
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
