# Generated by Django 4.2.1 on 2023-06-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0010_alter_userchat_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdffile",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
