# Generated by Django 4.2.1 on 2023-10-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0011_pdffile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_info', models.CharField(max_length=100)),
                ('created_at', models.DateField()),
            ],
        ),
    ]
