# Generated by Django 4.2.1 on 2023-10-30 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0012_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchat',
            name='prompt_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.prompt'),
        ),
    ]
