# Generated by Django 4.2.1 on 2023-10-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0013_userchat_prompt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchat',
            name='sources',
            field=models.TextField(null=True),
        ),
    ]
